name: Execute Swift package command-line tool

on:
  push:
    branches: [ main ]

jobs:
  run-cli-tool:

    runs-on: macos-latest

    steps:
    - name: Install Mint
      run: |
          brew install mint
          mint run nicklockwood/SwiftFormat@0.49.1 --verbose .
